export const themeColors: {
  primary: { light: string; dark: string };
  'primary-hover': { light: string; dark: string };
  'primary-active': { light: string; dark: string };
  background: { light: string; dark: string };
  surface: { light: string; dark: string };
  'surface-elevated': { light: string; dark: string };
  'surface-1': { light: string; dark: string };
  'surface-2': { light: string; dark: string };
  'surface-3': { light: string; dark: string };
  foreground: { light: string; dark: string };
  'foreground-secondary': { light: string; dark: string };
  'foreground-tertiary': { light: string; dark: string };
  'foreground-disabled': { light: string; dark: string };
  'foreground-inverse': { light: string; dark: string };
  'foreground-on-primary': { light: string; dark: string };
  muted: { light: string; dark: string };
  border: { light: string; dark: string };
  'border-subtle': { light: string; dark: string };
  'border-strong': { light: string; dark: string };
  'border-light': { light: string; dark: string };
  success: { light: string; dark: string };
  warning: { light: string; dark: string };
  danger: { light: string; dark: string };
  error: { light: string; dark: string };
  info: { light: string; dark: string };
  'success-bg': { light: string; dark: string };
  'warning-bg': { light: string; dark: string };
  'danger-bg': { light: string; dark: string };
  'info-bg': { light: string; dark: string };
  'lego-dialogue': { light: string; dark: string };
  'lego-character': { light: string; dark: string };
  'lego-background': { light: string; dark: string };
  'lego-audio': { light: string; dark: string };
  'lego-fx': { light: string; dark: string };
  'lego-choice': { light: string; dark: string };
  'lego-condition': { light: string; dark: string };
  'lego-variable': { light: string; dark: string };
  'lego-loop': { light: string; dark: string };
  'lego-transition': { light: string; dark: string };
  hover: { light: string; dark: string };
  pressed: { light: string; dark: string };
  focus: { light: string; dark: string };
  selected: { light: string; dark: string };
  overlay: { light: string; dark: string };
  scrim: { light: string; dark: string };
  backdrop: { light: string; dark: string };
  'dialogue-bg': { light: string; dark: string };
  'name-bg': { light: string; dark: string };
  'name-text': { light: string; dark: string };
  'choice-bg': { light: string; dark: string };
  'choice-border': { light: string; dark: string };
  'choice-hover': { light: string; dark: string };
  'editor-canvas': { light: string; dark: string };
  'editor-grid': { light: string; dark: string };
  'editor-toolbar': { light: string; dark: string };
  'editor-panel': { light: string; dark: string };
  'editor-ruler': { light: string; dark: string };
  'shadow-xs': { light: string; dark: string };
  'shadow-sm': { light: string; dark: string };
  'shadow-md': { light: string; dark: string };
  'shadow-lg': { light: string; dark: string };
  'shadow-xl': { light: string; dark: string };
  'shadow-glow': { light: string; dark: string };
  'surface-container': { light: string; dark: string };
  'secondary': { light: string; dark: string };
};

declare const themeConfig: {
  themeColors: typeof themeColors;
};

export default themeConfig;
